### ISSUE TITLE
Wrong path to repository

### ISSUE THREAD

**Issue by sevrugin** [openlumi/openwrt-packages#1]
Hey!
I tried your instruction and added `https://openlumi.github.io/openwrt-packages/packages/arm_cortex-a9_neon/` to my `/etc/opkg/customfeeds.conf` but it doesn't work
But `https://openlumi.github.io/openwrt-packages/packages/` path works good.

**Comment by G1K** [comment]
The path is fixed and changed. Separately for 19.07 and snapshot
